GET {{HOST}}/users

GET {{HOST}}/users/1007c0c0-b6a0-4e0d-9d28-b9a1f8abe100

POST {{HOST}}/users
Content-Type: application/json
{
    "email": "test2@test.test",
    "username": "username2",
    "password": "password"
}

PATCH {{HOST}}/users/7f573bd5-d31f-4d9d-b076-5dd4d71a95b1
Content-Type: application/json
{
    "username": "username1"
}

DELETE {{HOST}}/users

GET {{HOST}}/categories

GET {{HOST}}/categories/a35fde65-4e3f-41b0-842a-2076b8ef4c6e

POST {{HOST}}/categories
Content-Type: application/json
{
    "name": "category name 1", 
    "created_by_id": "cc939987-0168-4814-b6ff-695e2436d07c"
}

DELETE {{HOST}}/categories/a35fde65-4e3f-41b0-842a-2076b8ef4c6e